{% set name = "mmtf-python" %}
{% set version = "1.1.2" %}
{% set sha256 = "a5caa7fcd2c1eaa16638b5b1da2d3276cbd3ed3513f0c2322957912003b6a8df" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - msgpack-python

test:
  imports:
    - mmtf
    - mmtf.api
    - mmtf.codecs
    - mmtf.codecs.decoders
    - mmtf.codecs.encoders
    - mmtf.converters
    - mmtf.tests
    - mmtf.utils

about:
  home: http://mmtf.rcsb.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'A decoding library for the PDB mmtf format'
  description: |
    The macromolecular transmission format (MMTF) is a binary encoding of
    biological structures. This repository holds the Python 2 and 3 compatible
    API, encoding and decoding libraries.
  doc_url: https://rcsb.github.io/mmtf-python/docs/api/v1.0.0/
  dev_url: https://github.com/rcsb/mmtf-python

extra:
  recipe-maintainers:
    - kain88-de
    - orbeckst
    - richardjgowers
