travis:
  secure:
    BINSTAR_TOKEN: kf68kXkILNcXfRMXTBlxNH53+gKFtq2XU/770367ObFYlc3v3C827UMgIpo6osPDP1gkmoYLxVXylXL3x+P1yLJJpTsvuza3iZ1frRSSdwBPxnbAO6NLeot+eF800lx67n8tNB+Q1GO7/x6C+swFS5cchE0DQyh3pz+/U3LGXr9GQ7fW/ooXERemel5oEA3m7g5v4ctqJp0PMj0k4BS/M7Somlp88hWobsgIAIiLaTYHm/DeAwGtr73BRd6DW5vKemMPsosSQBmAywcYQLKImRfb5/1GmSfonAqjIWj1i4btXKjL/XfoB6yUUq809lDvdZwptmsLjKlwGucHG86fReIw1uTKI/pZaFIMbWGKJoUtsk1oiUDZr3ZvPheLl9h54Cd6cAwo4a/ucYzVFmjVs0Kxr4R08vSOnS19x/ibX8Th/KfsC+6F0rAeQRywaVmE74tZmXkJ3ZasAgn9qmvlh+R1Z1GySigUxqsSlixGy98MFUx+YNII4CNAK4lgwXIYg5Fep+pFCdKfwIvwTcczCAQYQZ7lAwPE3zAez021+qDfFvZlYNaWxjHxepqAowCiKjoVhvTdIaIXipIjff6zc3HcMaHvv43f/fTqB9y2VrW+PwIi//VDGQPuFOHiCl88XfmWl0WHB7b/+1tQsv5j4HUr21IP8/O3te/B2Pn8NVI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
