travis:
  secure:
    BINSTAR_TOKEN: rNVWaPId0zagNe7baPQThUYUpHJtNohLojVhi9GFcWYdGZpJnufNMZkPyz7GBriPVu/t8bYfOtqb2Gap3YFZoyOPVHH5MOMdS6Vc7VGtjxNyRYVCpN6PCeCjX+viIG89MsJoX5trBtTvSt3CBKr+jyUfW81LwqoIoWlS1EAtT5GfX82IhQzPoK0Cd9mhVZuewVrc2sNjGr3aXthuAuJ1JPPc63InJbYoyWk4z7KJE8fVFTQkftFlOMTDTHnVysCMHwYbFWjJd0J5yU6OPHjmDk9pAe7yYjNGJhUcA8h8sX1hRbf927jTYAGzBKErVLmVyaKeIWGKY9dZVH6k4V0yecFB+8yJDdfF3GLqT2ccq+vmyZFyny/Iojq+PJETKCoAUGECdPF+qBEGJs48ktF3OH0/E69SwLuvDA0erwPlIRWOu3Vo4lrA4wU9LNe700N52AvpPC7kxVSIcqmAMejubRAX5d3Qirw/7e9aalvrJIJkTrPdbgS0SNi3uPTJNgPtGG9mKzfv3GKfg8wAVjajlM1HsDDT1U1lQFs9O2J3V5wDic2GVHTmTlsu4DQs1wa7liesJqxXoWQJPqsJ/QDD5k7j83CfnPUCBmIPpU1KNIlTp7nt4SxhFGIBKC38bkUp5buuXt03BiaKUfiAi6Y+pQpGHPEQGgYv9/d8viB4coA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
